[build]
  publish = "." # This tells Netlify where your built website files are (your HTML file)
  functions = "netlify/functions" # This tells Netlify where your serverless functions are located
  command = "npm install" # Tells Netlify to install Node.js dependencies
