[build]
  publish = "." # This tells Netlify where your built website files are (your HTML file)
  functions = "netlify/functions" # This tells Netlify where your serverless functions are located

[[redirects]]
  from = "/.netlify/functions/get-weather"
  to = "/.netlify/functions/get-weather"
  status = 200
